security:
    # Ustawienia hashowania haseł
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: auto

    # Dostawca użytkowników
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            # Usuń lub skomentuj `http_basic`
            # http_basic:
            #     realm: 'My Secured Area'

            # Dodaj konfigurację `form_login`
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: home_index
                always_use_default_target_path: false
                username_parameter: _username
                password_parameter: _password
                csrf_token_id: authenticate
                enable_csrf: true

            logout:
                path: app_logout
                target: app_login

    # Reguły kontroli dostępu
    access_control:
        - { path: ^/, roles: PUBLIC_ACCESS }

    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_USER
            - ROLE_LOCATION_VIEW       # Może przeglądać lokalizacje
            - ROLE_LOCATION_EDIT       # Może edytować lokalizacje
            - ROLE_LOCATION_CREATE     # Może tworzyć nowe lokalizacje
            - ROLE_LOCATION_DELETE     # Może usuwać lokalizacje
            - ROLE_WEATHERDATA_VIEW    # Może przeglądać pomiary
            - ROLE_WEATHERDATA_EDIT    # Może edytować pomiary
            - ROLE_WEATHERDATA_CREATE  # Może tworzyć nowe pomiary
            - ROLE_WEATHERDATA_DELETE  # Może usuwać pomiary

        ROLE_USER:
            - ROLE_LOCATION_VIEW       # Może jedynie przeglądać lokalizacje
            - ROLE_WEATHERDATA_VIEW    # Może jedynie przeglądać pomiary
            - ROLE_LOCATION_SHOW

        ROLE_VIEWER:
            - ROLE_LOCATION_VIEW
            - ROLE_WEATHERDATA_VIEW