# config/validator/validation.yaml

App\Entity\Location:
  properties:
    city:
      - NotBlank:
          message: 'Nazwa miasta nie może być pusta.'
          groups: ['create', 'edit']
      - Length:
          max: 100
          maxMessage: 'Nazwa miasta nie może przekraczać {{ limit }} znaków.'
          groups: ['create', 'edit']
    country:
      - NotBlank:
          message: 'Kraj nie może być pusty.'
          groups: ['create', 'edit']
    latitude:
      - NotBlank:
          message: 'Szerokość geograficzna jest wymagana.'
          groups: ['create']
      - Range:
          min: -90
          max: 90
          notInRangeMessage: 'Szerokość geograficzna musi być pomiędzy {{ min }} a {{ max }}.'
          groups: ['create', 'edit']
    longitude:
      - NotBlank:
          message: 'Długość geograficzna jest wymagana.'
          groups: ['create']
      - Range:
          min: -180
          max: 180
          notInRangeMessage: 'Długość geograficzna musi być pomiędzy {{ min }} a {{ max }}.'
          groups: ['create', 'edit']

App\Entity\Weatherdata:
  properties:
    location:
      - NotNull:
          message: 'Musisz wybrać lokalizację.'
          groups: ['create', 'edit']
    timestamp:
      - NotBlank:
          message: 'Data nie może być pusta.'
          groups: ['create', 'edit']
      - Date:
          message: 'Nieprawidłowy format daty.'
          groups: ['create', 'edit']
    temperature_celsius:
      - NotBlank:
          message: 'Temperatura jest wymagana.'
          groups: ['create', 'edit']
      - Range:
          min: -50
          max: 60
          notInRangeMessage: 'Temperatura musi być pomiędzy {{ min }}°C a {{ max }}°C.'
          groups: ['create', 'edit']
    wind_speed:
      - NotBlank:
          message: 'Prędkość wiatru jest wymagana.'
          groups: ['create', 'edit']
      - Range:
          min: 0
          max: 150
          notInRangeMessage: 'Prędkość wiatru musi być pomiędzy {{ min }} km/h a {{ max }} km/h.'
          groups: ['create', 'edit']
    humidity:
      - NotBlank:
          message: 'Wilgotność jest wymagana.'
          groups: ['create', 'edit']
      - Range:
          min: 0
          max: 100
          notInRangeMessage: 'Wilgotność musi być pomiędzy {{ min }}% a {{ max }}%.'
          groups: ['create', 'edit']
    pressure:
      - NotBlank:
          message: 'Ciśnienie jest wymagane.'
          groups: ['create', 'edit']
      - Range:
          min: 900
          max: 1100
          notInRangeMessage: 'Ciśnienie musi być pomiędzy {{ min }} hPa a {{ max }} hPa.'
          groups: ['create', 'edit']
